name: 'lakehouse_transformation'
version: '1.0.0'
config-version: 2

profile: 'lakehouse_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

on-run-end:
  - "{{ elementary.upload_run_results() }}"
  - "{{ log_dbt_run_results(results) }}"

models:
  lakehouse_transformation:
    +persist_docs:
      relation: true
      columns: true

    staging:
      +materialized: view
      +schema: staging
    # 2. Intermediate bersifat ephemeral (tidak ditulis ke BigQuery, hanya sebagai CTE)
    intermediate:
      +materialized: ephemeral
    # 3. Marts adalah tabel final yang akan di-materialize (di-save sebagai tabel di BigQuery)
    marts:
      +materialized: table
  elementary:
    +schema: elementary
