
lakehouse_profile:
  target: bigquery  # default target (bisa dioverride: dbt run --target snowflake)
  outputs:
    bigquery:
      type: bigquery
      method: oauth                          # gunakan gcloud ADC (Application Default Credentials)
      project: project-aaa919f1-4345-401b-860
      dataset: ecommerce_gold               # Gold layer output dataset
      location: asia-southeast2
      threads: 4
      timeout_seconds: 300
      priority: interactive

    snowflake:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"       # format: orgname-accountname
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      database: LAKEHOUSE_RAW
      warehouse: LAKEHOUSE_WH
      schema: GOLD                                         # Gold layer output schema
      threads: 4
      client_session_keep_alive: false

elementary:
  target: bigquery
  outputs:
    bigquery:
      type: bigquery
      method: oauth
      project: project-aaa919f1-4345-401b-860
      dataset: elementary
      location: asia-southeast2
      threads: 4
      timeout_seconds: 300
      priority: interactive
